// Code generated by qtc from "ad_base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Advertisement base elements
//

//line private/templates/ad_base.qtpl:4
package templates

//line private/templates/ad_base.qtpl:4
import (
	"github.com/geniusrabbit/adcorelib/adtype"
	"github.com/geniusrabbit/adcorelib/eventtraking/events"
)

//line private/templates/ad_base.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line private/templates/ad_base.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line private/templates/ad_base.qtpl:11
var Debug bool
var URLGen adtype.URLGenerator

//line private/templates/ad_base.qtpl:15
func streamadActionScript(qw422016 *qt422016.Writer) {
//line private/templates/ad_base.qtpl:15
	qw422016.N().S(`<script type="text/javascript">var t = new Date();function e(u, st) {var delta = new Date() - t;var qPixel = new Image();qPixel.src = u+'&r='+st+'&d='+delta;};</script>`)
//line private/templates/ad_base.qtpl:24
}

//line private/templates/ad_base.qtpl:24
func writeadActionScript(qq422016 qtio422016.Writer) {
//line private/templates/ad_base.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_base.qtpl:24
	streamadActionScript(qw422016)
//line private/templates/ad_base.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_base.qtpl:24
}

//line private/templates/ad_base.qtpl:24
func adActionScript() string {
//line private/templates/ad_base.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_base.qtpl:24
	writeadActionScript(qb422016)
//line private/templates/ad_base.qtpl:24
	qs422016 := string(qb422016.B)
//line private/templates/ad_base.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_base.qtpl:24
	return qs422016
//line private/templates/ad_base.qtpl:24
}

//line private/templates/ad_base.qtpl:26
func streamadHeader(qw422016 *qt422016.Writer) {
//line private/templates/ad_base.qtpl:26
	qw422016.N().S(`<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><meta charset="utf-8" /><style type="text/css">*, body, html { margin: 0; padding: 0; border:none; }body, html { width: 100%; height: 100%; background: transparent }iframe[seamless] {background-color: transparent;border: 0px none transparent;padding: 0px;overflow: hidden;margin: 0;}</style></head><body>`)
//line private/templates/ad_base.qtpl:42
	streamadActionScript(qw422016)
//line private/templates/ad_base.qtpl:43
}

//line private/templates/ad_base.qtpl:43
func writeadHeader(qq422016 qtio422016.Writer) {
//line private/templates/ad_base.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_base.qtpl:43
	streamadHeader(qw422016)
//line private/templates/ad_base.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_base.qtpl:43
}

//line private/templates/ad_base.qtpl:43
func adHeader() string {
//line private/templates/ad_base.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_base.qtpl:43
	writeadHeader(qb422016)
//line private/templates/ad_base.qtpl:43
	qs422016 := string(qb422016.B)
//line private/templates/ad_base.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_base.qtpl:43
	return qs422016
//line private/templates/ad_base.qtpl:43
}

//line private/templates/ad_base.qtpl:46
func streamadFooter(qw422016 *qt422016.Writer) {
//line private/templates/ad_base.qtpl:46
	qw422016.N().S(`</body></html>`)
//line private/templates/ad_base.qtpl:48
}

//line private/templates/ad_base.qtpl:48
func writeadFooter(qq422016 qtio422016.Writer) {
//line private/templates/ad_base.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_base.qtpl:48
	streamadFooter(qw422016)
//line private/templates/ad_base.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_base.qtpl:48
}

//line private/templates/ad_base.qtpl:48
func adFooter() string {
//line private/templates/ad_base.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_base.qtpl:48
	writeadFooter(qb422016)
//line private/templates/ad_base.qtpl:48
	qs422016 := string(qb422016.B)
//line private/templates/ad_base.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_base.qtpl:48
	return qs422016
//line private/templates/ad_base.qtpl:48
}

// Generate pixel base code

//line private/templates/ad_base.qtpl:52
func streamadPixel(qw422016 *qt422016.Writer, adID, spotID, campID int, tag string) {
//line private/templates/ad_base.qtpl:52
	qw422016.N().S(`<script type="text/javascript">function u`)
//line private/templates/ad_base.qtpl:54
	qw422016.N().D(adID)
//line private/templates/ad_base.qtpl:54
	qw422016.N().S(`(st){}</script>`)
//line private/templates/ad_base.qtpl:56
}

//line private/templates/ad_base.qtpl:56
func writeadPixel(qq422016 qtio422016.Writer, adID, spotID, campID int, tag string) {
//line private/templates/ad_base.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_base.qtpl:56
	streamadPixel(qw422016, adID, spotID, campID, tag)
//line private/templates/ad_base.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_base.qtpl:56
}

//line private/templates/ad_base.qtpl:56
func adPixel(adID, spotID, campID int, tag string) string {
//line private/templates/ad_base.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_base.qtpl:56
	writeadPixel(qb422016, adID, spotID, campID, tag)
//line private/templates/ad_base.qtpl:56
	qs422016 := string(qb422016.B)
//line private/templates/ad_base.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_base.qtpl:56
	return qs422016
//line private/templates/ad_base.qtpl:56
}

// Generate pixel base code for adresult item

//line private/templates/ad_base.qtpl:60
func streamadPixelItem(qw422016 *qt422016.Writer, ad adtype.ResponserItem, resp adtype.Responser) {
//line private/templates/ad_base.qtpl:61
	if ad != nil && resp != nil {
//line private/templates/ad_base.qtpl:61
		qw422016.N().S(`<script type="text/javascript">`)
//line private/templates/ad_base.qtpl:63
		var u, _ = URLGen.PixelURL(events.Impression, events.StatusSuccess, ad, resp, false)

//line private/templates/ad_base.qtpl:64
		var v, _ = URLGen.PixelURL(events.View, events.StatusSuccess, ad, resp, false)

//line private/templates/ad_base.qtpl:64
		qw422016.N().S(`function u`)
//line private/templates/ad_base.qtpl:65
		qw422016.N().D(int(ad.AdID()))
//line private/templates/ad_base.qtpl:65
		qw422016.N().S(`(st){e('`)
//line private/templates/ad_base.qtpl:65
		qw422016.N().S(u)
//line private/templates/ad_base.qtpl:65
		qw422016.N().S(`',st)}function v`)
//line private/templates/ad_base.qtpl:66
		qw422016.N().D(int(ad.AdID()))
//line private/templates/ad_base.qtpl:66
		qw422016.N().S(`(st){e('`)
//line private/templates/ad_base.qtpl:66
		qw422016.N().S(v)
//line private/templates/ad_base.qtpl:66
		qw422016.N().S(`',st)}</script>`)
//line private/templates/ad_base.qtpl:68
	}
//line private/templates/ad_base.qtpl:69
}

//line private/templates/ad_base.qtpl:69
func writeadPixelItem(qq422016 qtio422016.Writer, ad adtype.ResponserItem, resp adtype.Responser) {
//line private/templates/ad_base.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_base.qtpl:69
	streamadPixelItem(qw422016, ad, resp)
//line private/templates/ad_base.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_base.qtpl:69
}

//line private/templates/ad_base.qtpl:69
func adPixelItem(ad adtype.ResponserItem, resp adtype.Responser) string {
//line private/templates/ad_base.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_base.qtpl:69
	writeadPixelItem(qb422016, ad, resp)
//line private/templates/ad_base.qtpl:69
	qs422016 := string(qb422016.B)
//line private/templates/ad_base.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_base.qtpl:69
	return qs422016
//line private/templates/ad_base.qtpl:69
}

//line private/templates/ad_base.qtpl:72
func streampreloader(qw422016 *qt422016.Writer) {
//line private/templates/ad_base.qtpl:72
	qw422016.N().S(`<style>.loading {position: absolute;height: 100%;width: 100%;top: 0;left: 0;background: #fefefe;display: block;z-index: 1000;}.loading .progress {position: fixed;display: block;width: 100%;height: 1.5pt;background: deepskyblue;}.loading .progress:before {content: "";position: absolute;left: 0;top: 0;width: 100%;height: 100%;transform: translateX(-100%);background: #ccc;animation: progress 3s ease infinite;}.loading .badge {position: absolute;left: 50%;top: 50%;display: block;padding: 3pt;margin: -15pt 0 0 -15pt;border: 1.5pt solid #ddd;border-radius: 5pt;font-family: Helvetica,sans-serif;font-size: 12pt;color: #ddd;}@-webkit-keyframes progress {50% {-webkit-transform: translateX(0%);transform: translateX(0%);}100% {-webkit-transform: translateX(100%);transform: translateX(100%);}}@keyframes progress {50% {-webkit-transform: translateX(0%);transform: translateX(0%);}100% {-webkit-transform: translateX(100%);transform: translateX(100%);}}}</style><div id="loadingBlock" class="loading"><div class="progress"></div><div class="badge">ADS</div></div>`)
//line private/templates/ad_base.qtpl:142
}

//line private/templates/ad_base.qtpl:142
func writepreloader(qq422016 qtio422016.Writer) {
//line private/templates/ad_base.qtpl:142
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_base.qtpl:142
	streampreloader(qw422016)
//line private/templates/ad_base.qtpl:142
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_base.qtpl:142
}

//line private/templates/ad_base.qtpl:142
func preloader() string {
//line private/templates/ad_base.qtpl:142
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_base.qtpl:142
	writepreloader(qb422016)
//line private/templates/ad_base.qtpl:142
	qs422016 := string(qb422016.B)
//line private/templates/ad_base.qtpl:142
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_base.qtpl:142
	return qs422016
//line private/templates/ad_base.qtpl:142
}
